export default {
  slug: 'dulce-lima',
  name: 'Dulce Lima',
  tagline: 'Repostería Peruana · Madrid',
  category: 'Repostería',
  theme: {
    colors: {
      bg:      '#ffffff',
      surface: '#DFF3FA',
      primary: '#026b88',
      accent:  '#D4620A',
      text:    '#2A1005',
      muted:   '#7A5545',
    },
    fonts: {
      heading: {
        family: '"Lora", Georgia, serif',
        google: 'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,600;0,700;1,400&display=swap',
      },
      body: {
        family: '"Nunito", system-ui, sans-serif',
        google: 'https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700&display=swap',
      },
    },
  },
  social: [
    { platform: 'instagram', href: 'https://instagram.com/dulcelima.madrid' },
    { platform: 'tiktok',    href: 'https://tiktok.com/@dulcelima.madrid' },
    { platform: 'whatsapp',  href: 'https://wa.me/34613515064' },
  ],
  sections: ['hero', 'about', 'services', 'menu', 'recipes', 'contact'],
  nav: {
    initials: 'DL',
    subtitle: 'Repostería Peruana',
    transparent: false,
    cta: { label: 'Hacer un pedido', href: '#contact' },
    links: [
      { label: 'Nosotros',  href: '#about' },
      { label: 'Productos', href: '#services' },
      { label: 'Carta',     href: '#menu' },
      { label: 'Contacto',  href: '#contact' },
    ],
  },
  hero: {
    layout: 'split',
    badge: 'Repostería Peruana en Madrid',
    title: 'Dulces que',
    titleGlow: 'saben a Lima.',
    description: 'Tortas, alfajores y postres peruanos hechos a mano cada día. Con recetas de la abuela, ingredientes frescos y el cariño de quien lo hace con amor.',
    cta: { label: 'Ver productos', href: '#services' },
    ctaSecondary: { label: 'Hacer un pedido', href: '#contact' },
    stats: [
      { value: '+3 años', label: 'endulzando Madrid' },
      { value: '4.9 ★',  label: 'valoración media' },
      { value: '+200',   label: 'pedidos al mes' },
    ],
    images: [
      { src: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=600&h=900&fit=crop&q=80', label: 'Tortas',    bg: 'linear-gradient(135deg, #C4507A22, #C4507A55)' },
      { src: 'https://images.unsplash.com/photo-1624000961428-eeece184988b?w=400&h=400&fit=crop&q=80', label: 'Postres',   bg: 'linear-gradient(135deg, #C4882A22, #C4882A55)' },
      { src: 'https://images.unsplash.com/photo-1517400847543-fd27a32c8d12?w=400&h=400&fit=crop&q=80', label: 'Alfajores', bg: 'linear-gradient(135deg, #C4507A22, #C4507A44)' },
      { src: 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=400&h=400&fit=crop&q=80', label: 'Cupcakes',  bg: 'linear-gradient(135deg, #C4882A22, #C4882A44)' },
      { src: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&h=400&fit=crop&q=80',   label: 'Trufas',    bg: 'linear-gradient(135deg, #C4507A22, #C4507A33)' },
    ],
  },
  about: {
    bg: 'bg-demo-bg',
    label: 'Nuestra historia',
    title: 'Hecho con las manos,',
    titleHighlight: 'con receta de Lima.',
    paragraphs: [
      'Dulce Lima nació del deseo de Valeria Quispe de compartir los sabores que la acompañaron toda su infancia en Lima. Mazamorra morada, suspiro a la limeña, alfajores de maicena. Recetas que no se improvisan, se heredan.',
      'Desde nuestro obrador en Alcorcón elaboramos cada pieza a mano, sin prisas y sin atajos. Porque un buen dulce no se fabrica, se cuida.',
    ],
    features: [
      { icon: '🤲', title: 'Todo hecho a mano',         description: 'Ninguna pieza sale de una máquina. Cada dulce lo trabajamos desde cero en nuestro obrador.', dark: false },
      { icon: '🇵🇪', title: 'Recetas peruanas auténticas', description: 'Mazamorra, suspiro, alfajores de maicena. Recetas de Lima que no cambiamos por nada.', dark: true },
      { icon: '🌿', title: 'Ingredientes frescos',       description: 'Sin conservantes, sin colorantes artificiales. Lo que no usaríamos en casa, no lo usamos aquí.', dark: false },
      { icon: '📦', title: 'Pedidos personalizados',     description: 'Tortas de encargo, mesas dulces y cajas regalo. Cuéntanos qué necesitas.', dark: false },
    ],
    badge: { value: 'Lima', label: 'en cada bocado' },
    imagePlaceholder: 'Foto del obrador o los productos',
  },
  services: {
    label: 'Lo que más nos piden',
    title: 'Nuestros favoritos',
    layout: 'cards',
    cta: { label: 'Ver carta completa', href: '#menu' },
    items: [
      {
        title: 'Tortas de Encargo',
        badge: 'Encargo',
        description: 'Tortas decoradas para cumpleaños, bodas y celebraciones. Rellenos peruanos: tres leches, manjar blanco, lúcuma.',
        price: 'Desde 35 €',
      },
      {
        title: 'Suspiro a la Limeña',
        badge: 'Clásico',
        featured: true,
        featuredBadge: 'El más pedido',
        description: 'El postre más icónico del Perú. Manjar blanco de leche condensada con merengue italiano al oporto. Imposible resistirse.',
        price: 'Desde 4,50 €',
      },
      {
        title: 'Caja de Alfajores',
        badge: 'Regalo',
        description: 'Alfajores de maicena rellenos de manjar blanco casero. En caja de 6 o 12 unidades. El regalo perfecto.',
        price: 'Desde 12 €',
      },
    ],
  },

  menu: {
    label: 'Todo lo que hacemos',
    title: 'Nuestra carta',
    subtitle: 'Pedidos con 48 horas de antelación. Consulta disponibilidad por WhatsApp.',
    tabs: [
      {
        label: 'Tortas',
        layout: 'cards',
        items: [
          { name: 'Torta tres leches',     price: '35 €',  description: 'La reina de la repostería peruana. Esponjosa, húmeda, con crema chantilly.', badge: 'Encargo' },
          { name: 'Torta de lúcuma',       price: '38 €',  description: 'Bizcocho de vainilla con crema de lúcuma peruana. Fruta exótica, sabor único.' },
          { name: 'Torta de maracuyá',     price: '36 €',  description: 'Capas de bizcocho con mousse de maracuyá fresco. Ácida y golosa a la vez.' },
          { name: 'Torta personalizada',   price: 'Desde 40 €', description: 'Diseño y relleno a elegir. Contacta con nosotros para hablar de tu pedido.', badge: 'A medida' },
        ],
      },
      {
        label: 'Postres',
        layout: 'cards',
        items: [
          { name: 'Suspiro a la limeña',  price: '4,50 €', description: 'Manjar blanco con merengue al oporto. El clásico peruano por excelencia.', badge: 'Favorito' },
          { name: 'Mazamorra morada',     price: '3,90 €', description: 'Postre de maíz morado con frutas y canela. Dulce, suave y muy reconfortante.' },
          { name: 'Arroz con leche',      price: '3,50 €', description: 'Versión peruana: cremosa, con canela y un toque de coco.' },
          { name: 'Picarones',            price: '5,90 €', description: 'Buñuelos de camote y zapallo bañados en miel de chancaca. Ración de 4 unidades.' },
        ],
      },
      {
        label: 'Bocaditos',
        layout: 'simple',
        items: [
          { name: 'Alfajores de maicena', price: '2,00 €', description: 'Rellenos de manjar blanco casero. Unidad.' },
          { name: 'Caja de alfajores x6', price: '11 €',   description: 'Perfecta para regalar.' },
          { name: 'Trufas de chocolate',  price: '1,80 €', description: 'Con cobertura de cacao puro. Unidad.' },
          { name: 'Caja de trufas x8',    price: '13 €',   description: 'Surtido de sabores: chocolate, maracuyá y lúcuma.' },
          { name: 'Cupcake peruano',      price: '3,20 €', description: 'Base de bizcocho húmedo con frosting de manjar o lúcuma.' },
          { name: 'Mesa dulce',           price: 'Desde 80 €', description: 'Montaje completo para eventos. Consulta opciones.' },
        ],
      },
    ],
  },

  recipes: {
    label: 'Recetas de la casa',
    title: 'Aprende a hacerlo tú',
    subtitle: 'Mis recetas favoritas para que el sabor de Lima llegue también a tu cocina.',
    items: [
      {
        name: 'Suspiro a la Limeña',
        emoji: '🍮',
        description: 'El postre más icónico del Perú. Cremoso, dulce y con un toque de oporto.',
        time: '35 min',
        difficulty: 'Fácil',
        servings: '6 porciones',
        ingredients: [
          '1 lata de leche condensada (397 g)',
          '1 lata de leche evaporada (410 g)',
          '4 yemas de huevo',
          '1 cucharadita de vainilla',
          '4 claras de huevo',
          '200 g de azúcar',
          '4 cucharadas de vino de Oporto',
          'Canela molida para decorar',
        ],
        steps: [
          'En una olla a fuego medio, mezcla la leche condensada y la evaporada. Remueve constantemente hasta que espese y se despegue de los bordes (unos 15 min).',
          'Fuera del fuego, añade las yemas una a una sin dejar de remover. Agrega la vainilla y vuelve al fuego 2 min más. Vierte en copas o en una fuente y deja enfriar.',
          'Para el merengue, bate las claras a punto de nieve. En un cazo, haz un almíbar con el azúcar y 4 cucharadas de agua hasta llegar a 120 °C.',
          'Vierte el almíbar en hilo fino sobre las claras sin dejar de batir. Añade el Oporto al final y bate hasta que el merengue esté brillante y firme.',
          'Cubre el manjar con el merengue usando una manga o una cuchara. Espolvorea canela por encima y sirve a temperatura ambiente.',
        ],
        tip: 'La clave está en remover sin parar el manjar para que no se pegue. Si el merengue queda muy líquido, el almíbar no llegó a la temperatura correcta.',
      },
      {
        name: 'Alfajores de Maicena',
        emoji: '🍪',
        description: 'Tiernos, que se deshacen en la boca. Rellenos de manjar blanco casero.',
        time: '50 min',
        difficulty: 'Fácil',
        servings: '20 unidades',
        ingredients: [
          '200 g de maicena (fécula de maíz)',
          '100 g de harina de trigo',
          '100 g de mantequilla a temperatura ambiente',
          '80 g de azúcar glass',
          '2 yemas de huevo',
          '1 cucharadita de esencia de vainilla',
          '1 cucharadita de polvo de hornear',
          'Manjar blanco (dulce de leche) para el relleno',
          'Azúcar glass para decorar',
        ],
        steps: [
          'Bate la mantequilla con el azúcar glass hasta obtener una crema suave. Añade las yemas y la vainilla, mezcla bien.',
          'Incorpora la maicena, la harina y el polvo de hornear tamizados. Mezcla hasta obtener una masa suave que no se pegue. Si hace falta, añade una cucharada de leche.',
          'Envuelve la masa en film y refrigera 30 minutos.',
          'Precalienta el horno a 170 °C. Estira la masa con un rodillo hasta unos 5 mm de grosor y corta círculos con un cortapastas de unos 4 cm.',
          'Hornea 10-12 minutos, hasta que los bordes empiecen a dorarse ligeramente. Deja enfriar completamente sobre una rejilla.',
          'Une dos galletas con una cucharada generosa de manjar blanco. Espolvorea azúcar glass por encima.',
        ],
        tip: 'No los saques del horno dorados, deben verse casi blancos. Se terminan de secar al enfriar y quedan perfectamente tiernos.',
      },
      {
        name: 'Mazamorra Morada',
        emoji: '🍇',
        description: 'Postre tradicional peruano de maíz morado. Suave, aromático y lleno de color.',
        time: '45 min',
        difficulty: 'Media',
        servings: '8 porciones',
        ingredients: [
          '500 g de maíz morado seco (mazorcas o granos)',
          '2 litros de agua',
          '1 membrillo cortado en trozos',
          '1 manzana en trozos',
          '1 pera en trozos',
          '1 rama de canela',
          '4 clavos de olor',
          '200 g de azúcar (o al gusto)',
          '6 cucharadas de maicena disuelta en agua fría',
          'Jugo de 2 limones',
          'Canela molida para servir',
        ],
        steps: [
          'Hierve el maíz morado con la canela, los clavos y el membrillo en los 2 litros de agua durante 40 minutos a fuego medio.',
          'Cuela el líquido, desechando los sólidos. Vuelve el líquido morado a la olla.',
          'Añade el azúcar, la manzana y la pera en trozos. Lleva a ebullición a fuego medio.',
          'Agrega la maicena disuelta poco a poco sin dejar de remover, hasta que espese a tu gusto.',
          'Fuera del fuego, añade el jugo de limón. Sirve en copas, espolvoreado con canela molida. Puedes servir frío o templado.',
        ],
        tip: 'Cuanto más maíz morado uses, más intenso será el color y el sabor. Si no encuentras mazorcas enteras, los granos secos funcionan igual de bien.',
      },
    ],
  },

  contact: {
    label: 'Haz tu pedido',
    title: 'Cuéntanos qué necesitas.',
    subtitle: 'Respondemos en menos de 24h. Para pedidos urgentes, escríbenos por WhatsApp.',
    phone: '+34 613 51 50 64',
    email: 'hola@dulcelima.es',
    address: 'Calle Río Tajo, 3 · Alcorcón, Madrid',
    hours: 'Lu - Sa: 9:00 - 20:00 · Do: 10:00 - 15:00',
  },

  footer: {
    dark: false,
    copy: 'Dulce Lima © 2024. Repostería Peruana en Alcorcón, Madrid.',
  },
}
