export default {
  slug: 'laura-vidal',
  name: 'Laura Vidal',
  tagline: 'Belleza & Bienestar · Barcelona',
  category: 'Centro de Estética',
  theme: {
    colors: {
      bg:      '#F7F3EE',
      surface: '#EAE4DC',
      primary: '#7A9C84',
      accent:  '#2C1B0E',
      text:    '#2C1B0E',
      muted:   '#a08070',
    },
    fonts: {
      heading: {
        family: '"Playfair Display", Georgia, serif',
        google: 'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400&display=swap',
      },
      body: {
        family: '"DM Sans", system-ui, sans-serif',
        google: 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600&display=swap',
      },
    },
  },
  social: [
    { platform: 'instagram', href: 'https://instagram.com/lauravidal.estetica' },
    { platform: 'tiktok',    href: 'https://tiktok.com/@lauravidal.estetica' },
  ],
  sections: ['hero', 'about', 'services', 'gallery', 'contact'],
  nav: {
    initials: 'LV',
    subtitle: 'Estética',
    cta: { label: 'Reservar cita', href: '#contact' },
    links: [
      { label: 'Sobre mí',    href: '#about' },
      { label: 'Servicios',   href: '#services' },
      { label: 'Galería',     href: '#gallery' },
      { label: 'Contacto',    href: '#contact' },
    ],
  },

  hero: {
    layout: 'split',
    badge: 'Centro de Belleza · Barcelona',
    title: 'Más de 20 años',
    titleHighlight: 'cuidando tu bienestar',
    description: 'Tratamientos corporales y faciales personalizados en el corazón de Barcelona. Tecnología LPG, HIFU corporal y depilación láser con resultados reales.',
    cta: { label: 'Pedir cita', href: '#contact' },
    ctaSecondary: { label: 'Ver tratamientos', href: '#services' },
    stats: [
      { value: '20+', label: 'años de exp.' },
      { value: '594', label: 'seguidoras' },
      { value: 'LPG', label: 'autorizado' },
    ],
    images: [
      { src: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=600&h=900&fit=crop&q=80', label: 'Foto 01', bg: 'linear-gradient(135deg,#EAE4DC,#D4B896)' },
      { src: 'https://images.unsplash.com/photo-1516815989420-9cb5ef0fce78?w=400&h=400&fit=crop&q=80', label: 'Foto 02', bg: 'linear-gradient(135deg,#E8EEE9,#B8CBBC)' },
      { src: 'https://images.unsplash.com/photo-1695527081827-fdbc4e77be9b?w=400&h=400&fit=crop&q=80', label: 'Foto 03', bg: 'linear-gradient(135deg,#EDE8E1,#C9B8A2)' },
    ],
  },

  about: {
    label: 'Sobre el centro',
    title: 'Donde la ciencia y el bienestar se encuentran',
    paragraphs: [
      'Soy Laura Vidal, especialista en belleza y cuidado personal con más de dos décadas de experiencia. En mi centro del Carrer de Provença combino las últimas tecnologías con un enfoque totalmente personalizado.',
      'Cada cuerpo es diferente. Por eso diseño planes adaptados a tus objetivos, tu ritmo y tus necesidades reales. Sin promesas vacías, con resultados visibles.',
    ],
    features: [
      { icon: '✅', title: '+20 años de experiencia', description: 'Formación continua y dominio de las técnicas más avanzadas del sector.', dark: false },
      { icon: '⚡', title: 'Tecnología LPG',          description: 'Centro autorizado por LPG, líder mundial en tratamientos corporales.', dark: true },
      { icon: '💛', title: 'Trato personalizado',     description: 'Planes 100% adaptados a tu cuerpo, tus objetivos y tu momento de vida.', dark: false },
      { icon: '📍', title: 'Barcelona centro',        description: 'Carrer de Provença, 87. Fácil acceso en transporte público.', dark: false },
    ],
    cta: { label: 'Conoce tu plan', href: '#contact' },
  },
  
  services: {
    label: 'Tratamientos',
    title: 'Resultados reales para cada objetivo',
    subtitle: 'Tecnología de última generación con la cercanía de un trato artesanal.',
    layout: 'cards',
    ctaCard: {
      label: 'Personalizado',
      title: '¿No sabes qué tratamiento es para ti?',
      description: 'Te orientamos sin compromiso. Primera consulta gratuita.',
      button: { label: 'Pedir asesoramiento', href: '#contact' },
    },
    items: [
      { category: 'Corporal',     title: 'HIFU Corporal',          description: 'Ultrasonidos focalizados para reducir volumen y reafirmar sin cirugía.',                link: { label: 'Saber más', href: '#contact' } },
      { category: 'LPG',          title: 'Plan Corporal Completo', description: 'Combinación de tratamientos LPG adaptados a tu plan personalizado.',                   link: { label: 'Saber más', href: '#contact' } },
      { category: 'Depilación',   title: 'Depilación Láser',       description: 'Resultados permanentes con tecnología segura para todo tipo de piel.',                  link: { label: 'Saber más', href: '#contact' } },
      { category: 'Circulación',  title: 'Piernas Cansadas',       description: 'Tratamientos específicos para piernas hinchadas y pesadez circulatoria.',               link: { label: 'Saber más', href: '#contact' } },
      { category: 'Reafirmación', title: 'Reduce y Reafirma',      description: 'Planes adaptados para moldear la silueta y recuperar firmeza visible.',                 link: { label: 'Saber más', href: '#contact' } },
    ],
  },
  gallery: {
    label: 'Galería',
    title: 'Nuestro trabajo habla',
    layout: 'editorial',
    images: [
      { src: 'https://images.unsplash.com/photo-1695527081827-fdbc4e77be9b?w=600&h=900&fit=crop&q=80', alt: 'Sala de tratamientos', caption: 'Sala principal',    bg: 'linear-gradient(135deg,#EAE4DC,#D4B896)' },
      { src: 'https://images.unsplash.com/photo-1585945037805-5fd82c2e60b1?w=800&h=400&fit=crop&q=80', alt: 'Cosmética natural',    caption: 'Cosmética natural', bg: 'linear-gradient(135deg,#E8EEE9,#B8CBBC)' },
      { src: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=400&h=400&fit=crop&q=80',    alt: 'Zona relax',           caption: 'Facial premium',    bg: 'linear-gradient(135deg,#EDE8E1,#C9B8A2)' },
      { src: 'https://images.unsplash.com/photo-1516815989420-9cb5ef0fce78?w=400&h=400&fit=crop&q=80', alt: 'Tratamiento facial',   caption: 'Facial premium',    bg: 'linear-gradient(135deg,#EAE4DC,#D4B896)' },
      { src: 'https://images.unsplash.com/photo-1561212856-44e9bae482aa?w=400&h=400&fit=crop&q=80',    alt: 'Aromaterapia',         caption: 'Aromaterapia',      bg: 'linear-gradient(135deg,#E8EEE9,#B8CBBC)' },
      { src: 'https://images.unsplash.com/photo-1695527082039-5f96003b97e4?w=400&h=400&fit=crop&q=80', alt: 'Recepción',            caption: 'Bienvenida',        bg: 'linear-gradient(135deg,#D4B896,#A8896C)' },
    ],
  },
  contact: {
    label: 'Contacto',
    title: 'Da el primer paso hacia tu mejor versión',
    subtitle: 'Primera consulta gratuita. Te contactamos en menos de 24h.',
    phone: '612 345 678',
    email: 'hola@lauravidal.es',
    address: 'Carrer de Provença, 87 · Barcelona',
    hours: 'Lu - Vi · 9:00 - 20:00 · Sa · 10:00 - 15:00',
    widget: {
      nombre: 'Estética Vidal',
      tema: 'claro',
      colorFondo: '#ffffff',
      colorAcento: '#aa3bff',
      colorBorde: '#e5e4e7',
      tituloFormulario: 'Reservas',
      textoBtnReservar: 'Reservar',
      textoTelefono: 'También puedes reservar por teléfono',
      mostrarTelefono: true,
      temasGuardados: [],
      temasFavoritos: [],
      descripcion: '',
      links: ['', ''],
      logoUrl: '',
      mostrarNombre: false,
      mostrarPanelAyuda: false,
      colorNegocio: '#7c3aed',
      nombreSize: 'md',
      whatsapp: '34695078648',
      telefono: '+34695078648',
      minPersonas: 1,
      maxPersonas: 20,
      slotInterval: 30,
      antelacionMinHoras: 2,
      antelacionMaxDias: 30,
      aforoPorSlot: 0,
      cierreTemporalFecha: '',
      servicios: [],
      preguntasExtra: [],
      tituloPreguntasExtra: '',
      textoPoliticaPrivacidad: 'Política de Privacidad\n\nResponsable del tratamiento: [Nombre o razón social], con NIF [NIF], y dirección en [Dirección].\n\nFinalidad: Los datos personales recogidos a través de este formulario (nombre, teléfono, email) se utilizan exclusivamente para gestionar su reserva y contactar con usted al respecto.\n\nLegitimación: Ejecución de un contrato o solicitud precontractual (art. 6.1.b RGPD).\n\nConservación: Los datos se conservarán durante el tiempo necesario para gestionar la reserva y el período legal exigible.\n\nDestinatarios: No se cederán datos a terceros salvo obligación legal.\n\nDerechos: Puede ejercer sus derechos de acceso, rectificación, supresión, limitación y portabilidad enviando un correo a [email de contacto].',
      textoAvisoLegal: 'Aviso Legal\n\nTitular del sitio web: [Nombre o razón social]\nNIF: [NIF]\nDomicilio: [Dirección completa]\nEmail de contacto: [email]\n\nEl acceso y uso de este sitio web implica la aceptación de las presentes condiciones. El titular se reserva el derecho de modificar los contenidos sin previo aviso.\n\nEste sitio web ha sido desarrollado con la plataforma Reservaq (www.reservaq.com).',
      horarios: {
        0: [{ start: '12:00', end: '22:00' }],
        1: [],
        2: [{ start: '12:00', end: '16:00' }],
        3: [{ start: '12:00', end: '16:00' }, { start: '19:00', end: '22:30' }],
        4: [{ start: '12:00', end: '16:00' }, { start: '19:00', end: '22:30' }],
        5: [{ start: '12:00', end: '23:00' }],
        6: [{ start: '12:00', end: '23:00' }],
      },
      fechasBloqueadas: [],
      perfil: 'reserva',
      googleCalendarLink: false,
      modoEnvio: 'email',
      emailNegocio: 'jesus.9019@gmail.com',
      emailConfirmacion: true,
      encabezadoMensaje: '🍽️ *Nueva Reserva*',
      textoPie: '✅ ¡Gracias! Reserva hecha.',
      camposActivos: { nombre: true, apellidos: false, telefono: true, email: true, personas: true, fecha: true, hora: true, mensaje: true },
      mensajeTemplate: '{encabezado}\n\n👤 Nombre: {nombre}\n📞 Teléfono: {telefono}\n👥 Personas: {personas}\n🕐 Hora: {hora}\n📅 Día: {dia}\n{mensajeExtra}\n{pie}',
    },
  },
  footer: {
    dark: true,
    columns: [
      {
        brand: true,
        text: 'Centro de belleza y bienestar en Barcelona. Más de 20 años transformando cuerpos y vidas.',
      },
      {
        title: 'Navegación',
        links: [
          { label: 'Sobre mí',  href: '#about' },
          { label: 'Servicios', href: '#services' },
          { label: 'Galería',   href: '#gallery' },
          { label: 'Contacto',  href: '#contact' },
        ],
      },
      {
        title: 'Contacto',
        info: ['612 345 678', 'Carrer de Provença, 87', 'Barcelona'],
      },
    ],
    copy: '© 2026 Laura Vidal · Belleza & Bienestar',
  },
}
